Update Azure Function integration article
crate/crate-howtos pull request #285
Opened 2021-04-16 12:23 UTC by hammerhead

## Summary of the changes / Why this is an improvement
* Added a few more hints on where to find certain settings/what exactly to change in the config files
* Provide a concrete test payload
* There were a few issues with the actual function definition:
  * Some undefined variables were used
  * Timestamps were not handled correctly
  * The structure of the `context` object likely has changed over time

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

2021-04-19 16:31 UTC, amotl requested changes
Hi Niklas,

thanks a stack for giving this piece some love - both for improving the prose and for fixing code issues. I added some comments as minor suggestions.

With kind regards,
Andreas.

2021-04-19 16:31 UTC, amotl commented on docs/integrations/azure-functions.rst
> +`Azure CLI`_. All settings shown above within the `Values` object need to be set
```suggestion
`Azure CLI`_. All settings shown above within the ``Values`` object need to be set
```

2021-04-19 16:31 UTC, amotl commented on docs/integrations/azure-functions.rst
> +	// This is our Azure Function that will be called when new event hub messages are processed.
```suggestion
	// This is the Azure Function that will be called when new event hub messages are processed.
```

2021-04-19 16:31 UTC, amotl commented on docs/integrations/azure-functions.rst
> +a new device and send a device-to-cloud (D2C) message for test purposes.
```suggestion
a new device and send a device-to-cloud (D2C) message for testing purposes.
```

2021-04-20 06:01 UTC, hammerhead commented
Thanks for the feedback @amotl, I've pushed an updated version with your changes incorporated.

2021-04-20 13:11 UTC, amotl approved these changes
👍

2021-04-20 13:14 UTC, merged

2021-04-20 13:14 UTC, matthijskrul approved these changes

2021-04-20 13:14 UTC, matthijskrul commented on docs/integrations/azure-functions.rst
> +account, selecting "Access keys" and copying one of the shown connection
```suggestion
account, selecting "Access keys", and copying one of the shown connection
```

2021-04-20 13:14 UTC, matthijskrul commented on docs/integrations/azure-functions.rst
> +The ``EventHubConnectionString`` can be copied from the
```suggestion

The ``EventHubConnectionString`` can be copied from the
```

2021-04-20 13:14 UTC, matthijskrul commented on docs/integrations/azure-functions.rst
> +up within the Azure Function App's **Application Settings** which can be found
```suggestion
up within the Azure Function App's **Application Settings**, which can be found
```

2021-04-20 13:14 UTC, matthijskrul commented on docs/integrations/azure-functions.rst
>  	// A pool of connections to CrateDB that our Azure Function can utilise.
```suggestion
	// A pool of connections to CrateDB that our Azure Function can utilize.
```

2021-04-20 13:15 UTC, matthijskrul commented
Dang you were just a few seconds too fast! 😁

2021-04-20 13:34 UTC, hammerhead commented
Too bad, I'll create a mini follow-up pull request for those missed changes.