Move and extend sharding and partitioning guide
crate/crate-howtos pull request #324
Opened 2023-09-08 18:12 UTC by karynzv

## Summary of the changes / Why this is an improvement
Rewrote the sharding and partitioning guide and moved it from getting started to best practices. For the getting started section, I'd suggest having a more high-level set of pages using the default configurations provided by CrateDB.
This page contains more detailed example to guide the new users in the sharding partitioning journey.

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2023-09-11 08:38 UTC, amotl requested changes
Dear Karyn,

thanks for this patch, I like the guiding attitude and the reading flow very much. While conducting a quick review, I've added a few suggestions. Feel free to use them or not, as you see fit.

With kind regards,
Andreas.

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +=====================================
Just a suggestion for a different page title, with one less "-ing" suffix.

```suggestion
.. _sharding-partitioning:

===============================
About Sharding and Partitioning
===============================
```

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +This page provides an in-depth guide on how to configure sharding and partitioning in CrateDB, presenting best practices and examples.
Just trimming line-length here.
```suggestion
Sharding and partitioning are techniques used to distribute data evenly across
multiple nodes in a cluster, ensuring data scalability, availability, and performance.
This page provides an in-depth guide on how to configure sharding and partitioning in
CrateDB, presenting best practices and examples.
```

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +partition as a set of shards. For each partition the number of shards defined
Just a suggestion for adding punctuation.

```suggestion
partition as a set of shards. For each partition, the number of shards defined 
```

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +Adding another row to the table with a different partition key (i.e. different
```suggestion
Adding another record to the table with a different partition key (i.e. different 
```

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +by ``CLUSTERED INTO x SHARDS`` are created, when a first row with a specific
```suggestion
by ``CLUSTERED INTO x SHARDS`` are created, when a first record with a specific 
```

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +Then, to calculate the number of shards, you should consider that each shard size should be between 5 - 100 GB and each node can only hold up to 1000 shards.
Line wrapping and a bit of wording.
```suggestion
Then, to calculate the number of shards, you should consider that the size of each
shard should roughly be between 5 - 100 GB, and that each node can only manage
up to 1000 shards.
```

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +to store time-series data with the following assumptions:
Line wrapping and wording.
```suggestion
To illustrate the steps above, let's use them on behalf of an example. Imagine
you want to create a *partitioned table* on a *three-node cluster* to store
time-series data with the following assumptions:
```

2023-09-11 08:38 UTC, amotl commented on docs/best-practices/configuring-sharding-partitioning.rst
> +close to the upper limit. With six shards, each shard will have 50 GB (300 GB / 6) which is closer to the middle of the recommended size range (5 - 100 GB).
Line wrapping and wording.
```suggestion
With three shards, each shard will hold 100 GB (300 GB / 3), which is too
close to the upper limit. With six shards, each shard will manage 50 GB
(300 GB / 6) of data, which is closer to the recommended size range (5 - 100 GB).
```

2023-09-12 08:48 UTC, hammerhead approved these changes

2023-09-12 12:38 UTC, hlcianfagna approved these changes

2023-09-12 12:55 UTC, amotl approved these changes

2023-09-12 12:55 UTC, merged